#pragma once

#include "StBodyR.h"
#include "StBodyL.h"
#include "StdLeg.h"
#include "StdLegLeft.h"
#include "StWalkBodyR.h"
#include "StWalkBodyL.h"
#include "StWalkLegR.h"
#include "StWalkLegL.h"
#include "JmpBodyL.h"
#include "JmpBodyR.h"
#include "JmpLegL.h"
#include "JmpLegR.h"
#include "StAtkBodyL.h"
#include "StAtkBodyR.h"
#include "StUpAtkBodyR.h"
#include "StUpAtkBodyL.h"
#include "StUpBodyR.h"
#include "StUpBodyL.h"
#include "Sitdown.h"
#include "SitdownL.h"
#include "SitdownMoveR.h"
#include "SitdownMoveL.h"
#include "SitdownAtk.h"
#include "SitdownAtkL.h"
#include "BombBodyR.h"
#include "BombBodyL.h"
#include "StdDie.h"
#include "Pick.h"

//heavy
#include "StHBodyL.h"
#include "StHBodyR.h"
#include "WlkHBodyL.h"
#include "WlkHBodyR.h"
#include "StHjmpBodyL.h"
#include "StHjmpBodyR.h"
#include "SitdownHL.h"
#include "SitdownHR.h"
#include "StHAtkL.h"
#include "StHAtkR.h"
#include "StHupAtkR.h"
#include "StHupAtkL.h"

#include "Stdup.h"
